apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h13aox3x8-nodejs
  janus-idp.io/tekton: h13aox3x8-nodejs
  backstage.io/kubernetes-id: h13aox3x8-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h13aox3x8-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
